print ("What is your first name?")
firstname = input()
print ("What is your surname?")
surname = input()
print ("How old are you?")
age = input()
print("What is your gender? (M, F, Prefer not to say)")
gender = input()
print ("Forename", firstname)
print ("Surname:", surname)
print ("Age:", age)
print ("Gender:", gender)
